name: Generate Schema

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Run './build.cmd GenerateSchema'
        run: ./build.cmd GenerateSchema

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'schema'
          message: 'Update schema'
          default_author: github_actions
